name: HxChat
version: '1.0'
main: dev.hxragi.hxchat.HxChat
api-version: '1.21.8'
folia-supported: true
description: Local and global chat for your server
author: hxragi

permissions:
  hxchat.admin:
    description: Permission for reload config
    default: op
  hxchat.format:
    description: Allows using MiniMessage formatting in chat
    default: op